### ISSUE TITLE
How do I generate more than one IDL file?

### ISSUE THREAD

**Issue by OpusK** [eProsima/Micro-XRCE-DDS-Gen#1]
Hi, all.

I use generators to convert IDL files that have a base type and use them well.
But, how do I generate more than one IDL file at the same time?

For example, Quaternion, Vector and Header topic are required to create an Imu topic.

```
typedef double sensor_msgs__Imu__double_array_9[9];

struct Imu
{
  std_msgs::msg::dds_::Header_ header_;
  geometry_msgs::msg::dds_::Quaternion_ orientation_;
  sensor_msgs__Imu__double_array_9 orientation_covariance_;
  geometry_msgs::msg::dds_::Vector3_ angular_velocity_;
  sensor_msgs__Imu__double_array_9 angular_velocity_covariance_;
  geometry_msgs::msg::dds_::Vector3_ linear_acceleration_;
  sensor_msgs__Imu__double_array_9 linear_acceleration_covariance_;
};  // struct Imu_
```

Is there a way to #include the corresponding idl file and generate it at once?
I looked it up my way, but there was no guide for this. Are there any related features?

If not, after generating for each base type, should I use them in combination at the source level?

**Comment by julianbermudez** [comment]
Hi @OpusK,
Right now we do not support multiple IDL generation, sorry. It is planning for the next release (~2 weeks approx.). Your solution looks right, generate both IDLs in a separate way and combine them at source level.

**Comment by OpusK** [comment]
Hi, @julianbermudez 

Is this feature added to this release(1.0.0beta2)?
If so, will there be a simple tutorial example?

**Comment by lemunozm** [comment]
Hi @OpusK 
Yes, this feature is added to release 1.0.0beta2 (now master).

Having two idl files `A.idl` and `B.idl` and type B needs type A, the following line will create the required serialization code:
```
$ micrortpsgen A.idl B.idl
```
