### ISSUE TITLE
Compatibility problems

### ISSUE THREAD

**Issue by ToRaVe** [eProsima/Micro-XRCE-DDS-Gen#20]
Good morning,

I use Micro-XRCE-DDS-Gen to generate a Publisher and a Subscriber for a client.
When I try to build these files, I get the following error:
```
error: too few arguments to function ‘uxr_init_udp_transport’
     if(!uxr_init_udp_transport(&transport, "172.16.204.109", 2018))
         ^~~~~~~~~~~~~~~~~~~~~~
In file included from /home/eafadm/micro-XRCE-DDS/client/include/uxr/client/transport.h:21:0,
                 from /home/eafadm/micro-XRCE-DDS/client/include/uxr/client/client.h:40,
                 from /home/eafadm/micro-XRCE-DDS/client/examples/Customclient/BotDataPublisher.c:24:
```

I cloned the generator as well as the client/agent from their respective master branches. Would you advise me to use a different version? Or is this going to be fixed?

Thank you

**Comment by ToRaVe** [comment]
I just saw the pull request. This fixed the problem, but there is a little bug. When generating a pub/sub from a custom idl file, there are two name tags datawriter_xml

**Comment by julianbermudez** [comment]
Hi @ToRaVe,

We are going to check and fix that bug as soon as possible..

**Comment by ToRaVe** [comment]
Hello @lemunozm & @julianbermudez,

That's the same version as on last commit on the develop branch, isn't it? I hope I'm not messing things up.
My .idl-file reads:
```
//#include "ActualVals.idl"
//#include "CtrlParam.idl"
//#include "RefSend.idl"
//#include "RobotState.idl"


struct BotData
{	
	string f_time_stamp;
	
	//ActualVals actual_values;
	//CtrlParam controller_parameter;
	//RefSend reference_values;
	//RobotState robot_state;
};
```
and in the datawriter_xml string I get in the publisher and subscriber when running `microxrceddsgen -example BotData.idl` looks like this:
```
const char* datawriter_xml = "<dds>"
                                 "<data_writer>"
                                     "<topic>"
                                         "<kind>NO_KEY</kind>"
                                         "<name>HelloWorldTopic</name>"
                                         "<name>BotDataPubSubTopic</name>"
                                         "<dataType>BotData</dataType>"
                                     "</topic>"
                                 "</data_writer>"
                             "</dds>";
```

**Comment by lemunozm** [comment]
Hi @ToRaVe, you are right. The line `"<name>HelloWorldTopic</name>"` must not exists in the datawriter and datareader xml. It was an error in the code generated. Its now fixed in develop.
Thanks for reporting it!
