### ISSUE TITLE
Who can give me an example Imu.idl

### ISSUE THREAD

**Issue by baozeng90** [eProsima/Micro-XRCE-DDS-Gen#23]
#include "geometry_msgs/msg/Quaternion.idl"
#include "geometry_msgs/msg/Vector3.idl"
#include "std_msgs/msg/Header.idl"

module sensor_msgs {
  module msg {
    typedef double double__9[9];
    struct Imu {
      std_msgs::msg::Header header;
      geometry_msgs::msg::Quaternion orientation;
      double__9 orientation_covariance;
      geometry_msgs::msg::Vector3 angular_velocity;
      double__9 angular_velocity_covariance;
      geometry_msgs::msg::Vector3 linear_acceleration;
      double__9 linear_acceleration_covariance;
    };
  };
};

1) I want use IMU with Micro-XRCE-DDS-client +MCU. So I must design Imu.idl(like Imu.msg in ROS2).Who can give me an example Imu.idl?
2) we're not support int ? There are many  *.msg include time stamp(Time.msg).
So *.idl files must include Time.idl
 struct Time {
      int32 sec;
      uint32 nanosec;
};

**Comment by BorjaOuterelo** [comment]
Hi @baozeng90 

1. If you have Imu.msg from ROS2. The ROS2 framework should be able to provide you with a corresponding IDL. There is a post regarding this: https://answers.ros.org/question/268396/ros2-generating-dds-idl-files-from-msg-ros-message-format

2. I dont understand the question. Do you need `int` support? That should be already on this generator tool the correspondence between IDL and C++ types can be found in https://www.omg.org/spec/CPP11/1.3/PDF
. Do you need to `#include` other IDL? That is supported by the tool.

**Comment by baozeng90** [comment]
@BorjaOuterelo I got it

**Comment by golizheh** [comment]
@BorjaOuterelo 
I have image.Idl as follow and I wan to generate fatrtps publisher and subscriber  by using fastrtpsgen, BUT it said int32 is not defined:
How can I find the correct .IDL file for ROS2 cam2image example:
// generated from rosidl_adapter/resource/msg.idl.em
// with input from sensor_msgs/msg/Image.msg


module sensor_msgs {
  module msg {
    /*
     * This message contains an uncompressed image
     * (0, 0) is at top-left corner of image
     */
    struct Image {
      /*
       * Header timestamp should be acquisition time of image
       * Header frame_id should be optical frame of camera
       * origin of frame should be optical center of cameara
       * +x should point to the right in the image
       * +y should point down in the image
       * +z should point into to plane of the image
       * If the frame_id here and the frame_id of the CameraInfo
       * message associated with the image conflict
       * the behavior is undefined
       */
      std_msgs::msg::Header header;

      /*
       * image height, that is, number of rows
       */
      long height;

      /*
       * image width, that is, number of columns
       */
      long width;

      /*
       * The legal values for encoding are in file src/image_encodings.cpp
       * If you want to standardize a new string format, join
       * ros-users@lists.ros.org and send an email proposing a new encoding.
       * Encoding of pixels -- channel meaning, ordering, size
       * taken from the list of strings in include/sensor_msgs/image_encodings.h
       */
      string encoding;

      /*
       * is this data bigendian?
       */
      uint8 is_bigendian;

      /*
       * Full row length in bytes
       */
      uint32 step;

      /*
       * actual matrix data, size is (step * rows)
       */
      sequence<uint8> data;
    };
  };
};

**Comment by baozeng90** [comment]
1.you must define Header.idl.
2.you must use IDL data types.
3.https://www.omg.org/spec/CPP11/1.3/PDF （page 5）
4.example for Imu.idl

#include "Header.idl"
#include "Quaternion.idl"
#include "Vector3.idl"
struct Imu
{
	Header      header;
	Quaternion  orientation;
	double      orientation_covariance[9];
	Vector3     angular_velocity;
	double      angular_velocity_covariance[9];
	Vector3     linear_acceleration;
	double      linear_acceleration_covariance[9];
};

**Comment by BorjaOuterelo** [comment]
@golizheh It seems you are taking the IDL generated but not its dependencies. `std_msgs::msg::Header header;`

The `std_msgs::msg::Header` is a type from a ROS 2 interface. It should be available to generate the Imu.idl if you depend on it.
