### ISSUE TITLE
Failing Micro-XRCE-DDS-Gen build

### ISSUE THREAD

**Issue by i-and** [eProsima/Micro-XRCE-DDS-Gen#29]
Hi!
I have Ubuntu 18.04.3 LTS, openjdk 11.0.4  and  I'm trying to compile the project for the first time. As a result, the following errors occur:
> Task :compileJava FAILED
warning: [options] source value 6 is obsolete and will be removed in a future release
warning: [options] target value 1.6 is obsolete and will be removed in a future release
warning: [options] To suppress warnings about obsolete options, use -Xlint:-options.
/home/and/dds/eProsima/xrce/Micro-XRCE-DDS-Gen/src/main/java/com/eprosima/uxr/idl/grammar/Context.java:58: error: cannot find symbol
        if(typedecl.getTypeCode().getKind() == TypeCode.KIND_STRUCT && typedecl.isInScope())
                                                       ^
  symbol:   variable KIND_STRUCT
  location: class TypeCode
/home/and/dds/eProsima/xrce/Micro-XRCE-DDS-Gen/src/main/java/com/eprosima/uxr/microxrceddsgen.java:291: error: cannot find symbol
            keyann.addMember(new AnnotationMember("value", new PrimitiveTypeCode(TypeCode.KIND_BOOLEAN), "true"));
                                                                                         ^
  symbol:   variable KIND_BOOLEAN
  location: class TypeCode
/home/and/dds/eProsima/xrce/Micro-XRCE-DDS-Gen/src/main/java/com/eprosima/uxr/microxrceddsgen.java:295: error: cannot find symbol
            topicann.addMember(new AnnotationMember("value", new PrimitiveTypeCode(TypeCode.KIND_BOOLEAN), "true"));
                                                                                           ^
  symbol:   variable KIND_BOOLEAN
  location: class TypeCode
/home/and/dds/eProsima/xrce/Micro-XRCE-DDS-Gen/src/main/java/com/eprosima/uxr/microxrceddsgen.java:298: error: constructor TemplateManager in class TemplateManager cannot be applied to given types;
            TemplateManager tmanager = new TemplateManager("Common");
                                       ^
  required: String,Context,boolean
  found: String
  reason: actual and formal argument lists differ in length
4 errors
3 warnings

**What can this be related to?**

**Comment by i-and** [comment]
To fix the error, I refused to compile the master branch for IDL-Parser. 

Can you share your plans for the development of Micro-XRCE-DDS-Gen? When you plan to support all remaining data structures (enum, unions, ...) and serialization in accordance with XCDR version 2.0 (@extensibility, ....)?

**Comment by JaimeMartin** [comment]
Hi @i-and ,

I have seen your questions & contributions and it would be nice to have a meeting to introduce each other. Send me an email and we can organize a quick one.

JaimeMartin@eProsima.com
