### ISSUE TITLE
BUILD ERROR

### ISSUE THREAD

**Issue by jinfeihan57** [eProsima/Micro-XRCE-DDS-Gen#42]
Can not build micro-xrce-dds-gen. build error.
using gradle 6.9.3 or 7.2. both are not support.

**Comment by Acuadros95** [comment]
Could you share the build error?

Please make sure that you are using the `develop` branch, as the fix for gradle 7.x has not been merged on master branch.

**Comment by jinfeihan57** [comment]
> Could you share the build error?
> 
> Please make sure that you are using the `develop` branch, as the fix for gradle 7.x has not been merged on master branch.

I use the fix/v2.0.0 branch, It works fine.
