### ISSUE TITLE
Avoid void casts on serialization error

### ISSUE THREAD

**Issue by Ryanf55** [eProsima/Micro-XRCE-DDS-Gen#45]
If I use `microxrceddsgen`, inside the serialization function, it discards errors. If there are errors serializing, I want that brought up to my application. 

Furthermore, certain coding standards like MISRA explicitly forbid this, unless there is a comment  explaining why it's being discarded (MISRA C:2012 Rule 17.7).

Current Behavior: 
```
bool ShapeType_serialize_topic(ucdrBuffer* writer, const ShapeType* topic)
{
    (void) ucdr_serialize_string(writer, topic->color);

    (void) ucdr_serialize_int32_t(writer, topic->x);

    (void) ucdr_serialize_int32_t(writer, topic->y);

    (void) ucdr_serialize_int32_t(writer, topic->shapesize);

    return !writer->error;
}
```

MISRA compliant Behavior:
```
bool ShapeType_serialize_topic(ucdrBuffer* writer, const ShapeType* topic)
{
    bool success = true;
    success &= ucdr_serialize_string(writer, topic->color);

    success &= ucdr_serialize_int32_t(writer, topic->x);

    success &= ucdr_serialize_int32_t(writer, topic->y);

    success &= ucdr_serialize_int32_t(writer, topic->shapesize);

    return success & (!writer->error);
}
```

I have a PR to submit that changes this. Let me know if you agree this is desirable behavior.

**Comment by Ryanf55** [comment]
If there is any good way to write tests to check this new logic, let me know.

**Comment by pablogs9** [comment]
https://github.com/eProsima/Micro-XRCE-DDS-Gen/pull/46 merged. Closing
