### ISSUE TITLE
How do I generate Sequnce for a specific message? (like DiagnosticArray)

### ISSUE THREAD

**Issue by OpusK** [eProsima/Micro-XRCE-DDS-Gen#5]
- [diagnotic_msgs/DiagnosticArray](http://docs.ros.org/api/diagnostic_msgs/html/msg/DiagnosticArray.html) 

Among the basic topics of ROS2 are the above message.
In the current generator, only the function name is converted.

What should I do in this case?
If you do not have one yet, will you support it later?

**Comment by sivantsiv** [comment]
Our experience is the same - DiagnosticArray_ data type cannot be used due to the multiple generation/compilation problems produced by Micro-RTPS Gen.
Please resolve it ASAP.
Thanks.

**Comment by lemunozm** [comment]
Hi @OpusK, @sivantsiv,
`Micrortpsgen` is only stable with basics types. We are working to add the support for the rest of the idl features. We upload it to master soon.

**Comment by lemunozm** [comment]
Hi @OpusK, @sivantsiv,
There is a pull request (#6) with new serialization capabilities for MicroRTPSGen. It is already working strings, sequences (only one level of depth at this moment) with strings or structs , and n-dimensional arrays.

The next IDL shows the current members that can be serialized with this update:
```c
struct TestType {
    float                      test_float;
    double                     test_double;
    short                      test_short;
    long                       test_long;
    long long                  test_long_long;
    unsigned short             test_unsigned_short;
    unsigned long              test_unsigned_long;
    unsigned long long         test_unsigned_long_long;
    char                       test_char;
    boolean                    test_boolean;
    octet                      test_octet;
    string                     test_string;
    CustomType                 test_custom;
    sequence<long>             test_seq_long;
    sequence<CustomType>       test_seq_custom;
    sequence<string>           test_seq_string;
    long                       test_array_long[2];
    CustomType                 test_array_custom[2];
    string                     test_array_string[2];
    long                       test_array_2_long[2][4];
    CustomType                 test_array_2_custom[2][4];
    string                     test_array_2_string[2][4];
    long                       test_array_3_long[2][4][8];
};
```
We will continue working for offer the remaining features of IDL to MicroRTPS (as unions or sequences over sequences)
