### ISSUE TITLE
Bug: int8 type does not generate correctly. 

### ISSUE THREAD

**Issue by Ryanf55** [eProsima/Micro-XRCE-DDS-Gen#54]
I have a simple message that does not work with int8 type. 

```idl
struct MyInt8 {
    int8 myInt8Field;
};
```

This message comes from the status field of [NavSatFix](https://docs.ros.org/en/melodic/api/sensor_msgs/html/msg/NavSatStatus.html), which is the de facto message for ROS2 position reporting in WGS-84 coordinates. It's used in many visualization tools, such as [Foxglove](https://foxglove.dev/docs/studio/panels/map#locationfix). 

MicroXRCEDDSGen has a crash trying to generate the type. 

Hash: 0eed89a87427d3faca9a05e61bf31509529d627d (latest develop)

Note: The char type does work, perhaps it's a missing alias? Note: In general, ROS2 uses the `uintN` and `intN` format for datatypes, which isn't tested. This request would apply to make sure all the alias types work. 

Here's the screenshot of the relevant part of the OMG IDL standard that shows it as a standard type. 
![image](https://user-images.githubusercontent.com/25047695/224471332-79feb1ba-cd9f-484d-99d7-c66db2a4378c.png)

**Comment by Acuadros95** [comment]
Fixed on https://github.com/eProsima/IDL-Parser/pull/68 merge.

**Comment by pablogs9** [comment]
https://github.com/eProsima/Micro-XRCE-DDS-Gen/pull/59 merged closing
