### ISSUE TITLE
Bug: PoseStamped.idl: Illegal identifier: geometry_msgs::msg::pose is already defined

### ISSUE THREAD

**Issue by Ryanf55** [eProsima/Micro-XRCE-DDS-Gen#56]
# Summary

This bug reports a illegal identifier when trying to generate PoseStamped. One theory is because `Pose and pose` are different cases, but treated the same. 

# Versioning

OS: Ubuntu 22.04
Hash: 0eed89a87427d3faca9a05e61bf31509529d627d
Message: ROS2 `geometry_msgs/msg/PoseStamped`

# Steps to reproduce

1. Take the ROS2 IDL's that make up PoseStamped, dump them in a single folder, and edit the includes to not have folders
2. Run the genretor on messages sequentially to build up PoseStamped.
    * ` microxrceddsgen Quaternion.idl`
    * ` microxrceddsgen Point.idl`
    *  ` microxrceddsgen Time.idl`
    *  ` microxrceddsgen Header.idl`
    *  ` microxrceddsgen Pose.idl`
    *  `microxrceddsgen PoseStamped.idl`
4. Observe this error:
```
$ microxrceddsgen libraries/AP_XRCE_Client/Idl/PoseStamped.idl
openjdk version "11.0.18" 2023-01-17
OpenJDK Runtime Environment (build 11.0.18+10-post-Ubuntu-0ubuntu122.04)
OpenJDK 64-Bit Server VM (build 11.0.18+10-post-Ubuntu-0ubuntu122.04, mixed mode, sharing)
Loading templates...
Processing the file libraries/AP_XRCE_Client/Idl/PoseStamped.idl...
libraries/AP_XRCE_Client/Idl/PoseStamped.idl:15:35: error: Illegal identifier: geometry_msgs::msg::pose is already defined (Definition: com.eprosima.idl.parser.tree.TypeDeclaration@6aeb35e6)
```

# Message Definition

## ROS2 .msg
```
$ ros2 interface show geometry_msgs/msg/PoseStamped
# A Pose with reference coordinate frame and timestamp

std_msgs/Header header
        builtin_interfaces/Time stamp
                int32 sec
                uint32 nanosec
        string frame_id
Pose pose
        Point position
                float64 x
                float64 y
                float64 z
        Quaternion orientation
                float64 x 0
                float64 y 0
                float64 z 0
                float64 w 1
 ```
 ## IDL
 ```
$ PoseStamped.idl 
// generated from rosidl_adapter/resource/msg.idl.em
// with input from geometry_msgs/msg/PoseStamped.msg
// generated code does not contain a copyright notice

#include "Pose.idl"
#include "Header.idl"

module geometry_msgs {
  module msg {
    @verbatim (language="comment", text=
      "A Pose with reference coordinate frame and timestamp")
    struct PoseStamped {
      std_msgs::msg::Header header;

      geometry_msgs::msg::Pose pose;
    };
  };
};
````

**Comment by Acuadros95** [comment]
You need to run the generator with the case sensitive `-cs` option.

I have added it on this PR: https://github.com/eProsima/Micro-XRCE-DDS-Gen/pull/61

**Comment by Acuadros95** [comment]
Closing as the fix is merged, feel free to reopen if any other problem appears

**Comment by dambrosio** [comment]
I have run into a similar issue trying to generate _.h_ and _.c_ files for ROS packages installed by default with the `ros-base` Humble variant.

If I copy all _.idl_ files from _/opt/ros/humble/share_ to _~/idl_:
```console
mkdir ~/idl
pushd /opt/ros/humble/share
find . -name "*.idl" -exec cp --parents {} ~/idl \;
```
I then get the following structure:
```console
❯ ls
rmw_dds_common
std_msgs
nav_msgs
map_msgs
...
```
If I attempt to run the `microxrceddsgen` script on all `.idl` files in _~/idl_:

```console
find idl -name "*.idl" -exec bash -c './micro-xrce-dds-gen/scripts/microxrceddsgen -cs -replace -I idl -d $(dirname "$1") "$1"' x {} \;
```
 **I get a bunch of Illegal identifier: <msg> is already defined** errors, **even** with the `-cs` flag specified.

For example:

```console
Processing the file idl/rmw_dds_common/msg/ParticipantEntitiesInfo.idl...
In file included from idl/rmw_dds_common/msg/NodeEntitiesInfo.idl:5:0,
                      idl/rmw_dds_common/msg/ParticipantEntitiesInfo.idl:6:0:
idl/rmw_dds_common/msg/Gid.idl:8:12: error: 'uint8' was redefined
In file included from idl/rmw_dds_common/msg/NodeEntitiesInfo.idl:5:0,
                      idl/rmw_dds_common/msg/ParticipantEntitiesInfo.idl:6:0:
idl/rmw_dds_common/msg/Gid.idl:9:15: error: Illegal identifier: rmw_dds_common::msg::Gid is already defined (Definition: com.eprosima.idl.parser.tree.TypeDeclaration@70cf32e3)
In file included from idl/rmw_dds_common/msg/NodeEntitiesInfo.idl:5:0,
                      idl/rmw_dds_common/msg/ParticipantEntitiesInfo.idl:6:0:
idl/rmw_dds_common/msg/Gid.idl:13:0: error: Unexpected input '}'
```

If I *just* generate from `.idl`s in `geometry_msgs`, everything works as expected:
```console
find idl/geometry_msgs -name "*.idl" -exec bash -c './micro-xrce-dds-gen/scripts/microxrceddsgen -cs -I idl -d $(dirname "$1") -replace "$1"' x {} \;
```

The packages with issues:

- `rmw_dds_common`
- `nav_msgs`
- `map_msgs`
- `tf2_msgs`
- `visualization_msgs`
- `sensor_msgs`
- `pcl_msgs`
- `stereo_msgs`
- `trajectory_msgs`
