### ISSUE TITLE
Allow for user-defined array sizes

### ISSUE THREAD

**Issue by Ryanf55** [eProsima/Micro-XRCE-DDS-Gen#68]
Right now, MicroXRCEDDSGen hard codes a size of 100 for arrays. 
```
typedef struct tf2_msgs_msg_TFMessage
{
    uint32_t transforms_size;
    geometry_msgs_msg_TransformStamped transforms[100];
} tf2_msgs_msg_TFMessage;
```

As a user, there is no way to adjust this at configure time. For an embedded system like ArduPilot, 100 transforms, or 100 joystick inputs, is far too many. We would like to configure these for our application. Perhaps through a define?

**Comment by pablogs9** [comment]
Hello @Ryanf55, this proposal LGTM, could you open a PR with a code proposal so we can discuss there?

**Comment by Ryanf55** [comment]
I don't actually have a great idea of how to do this without assuming the message structure/naming of ROS messages. Any recommendations are welcomed.

**Comment by pablogs9** [comment]
I'm gonna take a look internally to check the possibilities. I will report back.

**Comment by pablogs9** [comment]
This is the related PR removing this hardcoded "100" value: https://github.com/eProsima/IDL-Parser/pull/111

But this implies updating Micro-XRCE-DDS-Gen to latest IDL-Parser.

**Comment by srmainwaring** [comment]
@pablogs9, thanks for this change. I've used #74 to generate the bindings for the ArduPilot DDS library and it appears to work as expected on the two message types affected: `sensor_msgs/Joy` and `tf2_msgs/TFMessage`.
