### ISSUE TITLE
Suppress openjdk version printing on stderr

### ISSUE THREAD

**Issue by Ryanf55** [eProsima/Micro-XRCE-DDS-Gen#70]
When invoking microxrceddsgen on the command line, every time the version of openjdk is printed, to stderr. 

This clogs up our compilation logs with unrelated errors that are not errors. I only want errors to show up from MicroXRCEDDSGen if they are actual problems. 

Is there any way that MicroXRCEDDSGen could suppress the version info on stderr and redirect it to stdout or hide it entirely? 

```
$ microxrceddsgen -version > test.txt
openjdk version "11.0.20.1" 2023-08-24
OpenJDK Runtime Environment (build 11.0.20.1+1-post-Ubuntu-0ubuntu122.04)
OpenJDK 64-Bit Server VM (build 11.0.20.1+1-post-Ubuntu-0ubuntu122.04, mixed mode, sharing)
$ cat test.txt
microxrceddsgen version: 2.0.1
```

**Comment by pablogs9** [comment]
Does removing [this line](https://github.com/eProsima/Micro-XRCE-DDS-Gen/blob/b4190682216992eaf1f9b99fc4b54a21c72847ff/scripts/microxrceddsgen#L7) removes this log?

If it does, I'm ok with removing it.

**Comment by Ryanf55** [comment]
> Does removing [this line](https://github.com/eProsima/Micro-XRCE-DDS-Gen/blob/b4190682216992eaf1f9b99fc4b54a21c72847ff/scripts/microxrceddsgen#L7) removes this log?
> 
> If it does, I'm ok with removing it.

Yes! I'll submit a PR.
